### PR TITLE
switch to v3 format (fixes #14)

### LINKED ISSUE #14: switch to v3 syntax so non-ASCII can be used

### PR DESCRIPTION
**Pull request by reschke**
This is a mostly mechanical edit that makes the document valid v3.

### CODE REVIEW

**Comment by richsalz** [comment]
As WG chair, this should be done.  The RFC Editor will appreciate it.

**Comment by dret** [comment]
On Jun 13, 2021, at 16:40, Rich Salz ***@***.***> wrote:
> As WG chair, this should be done. The RFC Editor will appreciate it.

it's done already. @hvdsomp had it all lined up, but julian beat him to the finish line.

**Comment by jrlevine** [comment]
> As WG chair, this should be done. The RFC Editor will appreciate it.

Yes, this will make the editing faster and less likely to add format warts.

**Comment by richsalz** [comment]
> it's done already. @hvdsomp had it all lined up, but julian beat him to the finish line.

:)  love to see it.

**Comment by dret** [comment]
thanks, @reschke!

**Pull request merged**
